name: lovebirds_lens
description: A Flutter app for bird identification using AI
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  cached_network_image: ^3.3.0
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  intl: ^0.18.1
  flutter_staggered_animations: ^1.1.1
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
